### ISSUE TITLE
Change content in workshop page

### ISSUE THREAD

**Issue by rohithc123** [ACE-EEC/kratos-22-site#21]

**Comment by Dem1se** [comment]
Workshop section wont have cards. It will have a brochure like layout (kinda like a magazine), with images and paragraphs and other things to promote it, since there will only be a since workshop.

Having a card layout, just to contain a single card would look bad as it would imply we were planning to have multiple but only managed one. We should instead dedicate the entire page to this one workshop without any card bullshit.
